<?php
doQuery("INSERT INTO datasets (dataset_description) VALUES ('Generated by citation_uploader')");
$datasetId = mysql_insert_id();

if ($_FILES["citationFile"]["error"] > 0) {
	echo "Error: " . $_FILES["citationFile"]["error"] . "<br />";
} else {
	$fp = fopen($_FILES["citationFile"]["tmp_name"], 'r');
	$i = 0;
	while (($data = fgets($fp)) !== FALSE) {
		$index = strpos($data, ',');
		$id = substr($data, 0, $index);
		$text = addslashes(trim(substr($data, $index + 1)));
		doQuery("INSERT INTO citations (citation_id, citation_text, citation_dataset) VALUES ($id, '$text', $datasetId)");
		$i++;
	}
}
print "<P>Upload Complete.  $i records added.";
?>